### ISSUE TITLE
有没有像angularJS那样的全局请求拦截器？

### ISSUE THREAD

**Issue by zzbcoder** [RubyLouvre/mmRequest#23]
如题

**Comment by RubyLouvre** [comment]
什么叫全局请求拦截器，没有用过，请说明

**Comment by zbuddha** [comment]
类似jquery ajax全局设置，我想对后端错误做统一处理。
angular里有个 $httpProvider.interceptors.

**Comment by dragonwong** [comment]
@zbuddha 是类似 jq 的 `jQuery.ajaxSetup()` 么？现在 avalon 里面没有。

**Comment by dragonwong** [comment]
现已加上全局事件函数，详情请参考[文档](https://github.com/RubyLouvre/mmRequest/tree/master/docs) `Global event functions` 部分。
