### ISSUE TITLE
avalon.getScript 报错

### ISSUE THREAD

**Issue by dragonwong** [RubyLouvre/mmRequest#28]
使用 `avalon.getScript` 时会报错

**Comment by dragonwong** [comment]
fix：
1. 加载脚本无法执行回调；
2. ie7- 目标路径不支持相对路径；

**Comment by michaeljayt** [comment]
你的代码没有作合并。我已经发送合并后的PR，另外自此开始添加贡献说明。

**Comment by dragonwong** [comment]
@michaeljayt 我记得我直接在 mmRequest.js 上改过了（[这次 commit](https://github.com/RubyLouvre/mmRequest/commit/6f4e7d8ab4c7be84120441ab40cf10a62195bcb4)），anyway，谢谢你的提醒~~:smile:
