### ISSUE TITLE
关于avalon.ajax跨域

### ISSUE THREAD

**Issue by MaxMooc** [RubyLouvre/mmRequest#34]
var url='//172.16.7.58:7788/template/search/all';
            avalon.ajax({
                url:url + '/jsonp?callback=?',
                dataType: "jsonp",
                data: {},
                cache: true
            }).done(function(res) {
                avalon.log(res);
            }).fail(function(jqXHR, textStatus) {
                avalon.log(jqXHR );
            });

在浏览器network下可以看到返回数据，如：[{id:1},{id:2}],数组类型的字符串，但是程序不走done,只走fail，用jq也是只走error，不走success，应该是跨域的同类问题，请大神瞧瞧。谢谢

**Comment by dragonwong** [comment]
@MaxMooc 请注意下你服务端是否了对应的设置 :)

**Comment by MaxMooc** [comment]
OK    是后端的问题
