### ISSUE TITLE
method `unparam` broken

### ISSUE THREAD

**Issue by michaeljayt** [RubyLouvre/mmRequest#43]
After https://github.com/RubyLouvre/mmRequest/commit/5aa91b96d20dd1bfe75fded4685768b624268237 ,when input:

    avalon.unparam("?name=test")

Outputs:

    Object {?name: test}

Instead of:

    Object {name: test}

**Comment by dragonwong** [comment]
@michaeljayt 
手动去除问号吧，无论是 `param` 和 `unparam`，从语义上讲，都是不应该对问号进行处理的。

**Comment by michaeljayt** [comment]
OK but this change introduce a significant incompatible between old style and new one, why not set a `CHANGELOG` file to warn it?

**Comment by RubyLouvre** [comment]
已经处理
