### ISSUE TITLE
ajax的跨域问题

### ISSUE THREAD

**Issue by kiner-tang** [RubyLouvre/mmRequest#48]
请问除了jsonp方式解决跨域问题之外，还有别的方式可以解决吗？mmrequest中有没有提供其他方式解决跨域问题

**Comment by RubyLouvre** [comment]
https://forum.jquery.com/topic/workaround-for-break-in-ie10-11-cross-domain-patch-support

这里需要注意一下

**Comment by IndexXuan** [comment]
请问mmRequest有像jquery一样的设置headers的方法或者属性吗？有空能告知一下吗，貌似没在文档里看见啊。。。谢谢

**Comment by RubyLouvre** [comment]
jquery怎么设置，它就是怎么设置

**Comment by IndexXuan** [comment]
擦汗。。。 正妹老师百忙中都回复了，为啥不明说。试了headers{}, requestHeaders{}, beforeSend时设置，貌似都不行。您能看看吗? 感谢！

**Comment by RubyLouvre** [comment]
```javascript
avalon.ajax({/**/}).setResponseHeader("xx","yy")

avalon.get(a,b,c).setResponseHeader("xx","yy")

avalon.post(a,b,c).setResponseHeader("xx","yy")

```

get, post, getJSON,ajax方法都会返回promise对象，上面有一个setResponseHeader方法

**Comment by IndexXuan** [comment]
感谢回答。不过应该是发送请求前设置xhr.setRequestHeader（‘ ’， ‘ ’）,应该怎么设置。

**Comment by liufuhu** [comment]
为什么不把ajax放到avalon.js里？ 这是框架很基础的功能，为什么要分离开呢？

**Comment by RubyLouvre** [comment]
因为很多时候是与JQ一起使用，直接用JQ的就行了

**Comment by liufuhu** [comment]
ths
