### ISSUE TITLE
谷歌浏览器报错 ie is not defined

### ISSUE THREAD

**Issue by Mrlilili** [RubyLouvre/mmRequest#65]
Google Chrome	51.0.2704.106 (正式版本) （64 位）

这个版本version 0.41 by 司徒正美

![image](https://cloud.githubusercontent.com/assets/8361655/16707589/d09cc714-4606-11e6-83f4-b8fcae83f119.png)

引入mmRequest.modern.js就不会报错，
引入mmRequest.js就报错

**Comment by RubyLouvre** [comment]
你应该 贴全一点

**Comment by RubyLouvre** [comment]
修好了

**Comment by Mrlilili** [comment]
比方说，怎么样个全？我下次提问注意点，很少提问，不知所措
![image](https://cloud.githubusercontent.com/assets/8361655/16708349/f232378a-4622-11e6-8933-d4e23407328a.png)

**Comment by RubyLouvre** [comment]
把错误堆栈贴上来，及相关地方的源码，还有可以测试的页面
