### ISSUE TITLE
浏览器报错Uncaught TypeError: ajaxExtend is not a function

### ISSUE THREAD

**Issue by Mrlilili** [RubyLouvre/mmRequest#66]
avalon2.01
mmrequest0.43
Google Chrome	51.0.2704.106 (正式版本) （64 位）

![image](https://cloud.githubusercontent.com/assets/8361655/16771811/7a2f231a-4884-11e6-869d-c3a9b6690433.png)
![image](https://cloud.githubusercontent.com/assets/8361655/16771821/826a810a-4884-11e6-8eef-4f502d61737d.png)
demo地址：[戳我](http://mrlilili.github.io/other/mmrequestdebug/)

**Comment by RubyLouvre** [comment]
已修

**Comment by RubyLouvre** [comment]
升级
